# Generated by Django 4.2.7 on 2025-07-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='計画名')),
                ('dispatch_time', models.DateTimeField(verbose_name='発送時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '配送計画',
                'verbose_name_plural': '配送計画',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='荷主名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '荷主',
                'verbose_name_plural': '荷主',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='トラック名/番号')),
                ('bed_width', models.FloatField(verbose_name='荷台幅(cm)')),
                ('bed_depth', models.FloatField(verbose_name='荷台奥行き(cm)')),
                ('max_weight', models.FloatField(verbose_name='最大積載量(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'トラック',
                'verbose_name_plural': 'トラック',
            },
        ),
        migrations.CreateModel(
            name='TruckAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_order', models.JSONField(default=list, verbose_name='配送ルート順序')),
                ('total_distance', models.FloatField(default=0, verbose_name='総走行距離(km)')),
                ('estimated_time', models.FloatField(default=0, verbose_name='推定所要時間(分)')),
                ('delivery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_assignments', to='delivery.deliveryplan')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.truck')),
            ],
            options={
                'verbose_name': 'トラック割り当て',
                'verbose_name_plural': 'トラック割り当て',
                'unique_together': {('delivery_plan', 'truck')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('width', models.FloatField(verbose_name='幅(cm)')),
                ('height', models.FloatField(verbose_name='高さ(cm)')),
                ('depth', models.FloatField(verbose_name='奥行き(cm)')),
                ('weight', models.FloatField(verbose_name='重量(kg)')),
                ('destination_address', models.CharField(max_length=500, verbose_name='配送先住所')),
                ('delivery_deadline', models.DateTimeField(verbose_name='配送期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='delivery.shipper', verbose_name='荷主')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(verbose_name='X座標(cm)')),
                ('y_position', models.FloatField(verbose_name='Y座標(cm)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product')),
                ('truck_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='delivery.truckassignment')),
            ],
            options={
                'verbose_name': '商品割り当て',
                'verbose_name_plural': '商品割り当て',
                'unique_together': {('truck_assignment', 'product')},
            },
        ),
    ]
