# Generated by Django 4.2.7 on 2025-07-10 04:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='配送日')),
                ('departure_time', models.DateTimeField(verbose_name='出発予定時刻')),
                ('total_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載合計重量(kg)')),
                ('total_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載合計体積(cm³)')),
                ('route_distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='想定走行距離(km)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '配送計画',
                'verbose_name_plural': '配送計画',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配送先名')),
                ('address', models.CharField(max_length=500, verbose_name='住所（町丁目まで）')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='連絡先電話')),
            ],
            options={
                'verbose_name': '配送先',
                'verbose_name_plural': '配送先',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='品目コード')),
                ('name', models.CharField(max_length=100, verbose_name='製品名')),
                ('width', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='幅(cm)')),
                ('depth', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='奥行(cm)')),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='高さ(cm)')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='質量(kg)')),
                ('parts_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='セット品PCS数')),
            ],
            options={
                'verbose_name': '製品',
                'verbose_name_plural': '製品',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_code', models.CharField(max_length=100, unique=True, verbose_name='荷主コード')),
                ('name', models.CharField(max_length=200, verbose_name='荷主名')),
                ('address', models.CharField(max_length=500, verbose_name='住所')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='連絡先電話')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='連絡先メール')),
            ],
            options={
                'verbose_name': '荷主',
                'verbose_name_plural': '荷主',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='荷台幅(cm)')),
                ('depth', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='荷台奥行(cm)')),
                ('height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='荷台高さ(cm)')),
                ('payload', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最大積載量(kg)')),
                ('shipping_company', models.CharField(blank=True, max_length=256, verbose_name='運送会社名')),
                ('truck_class', models.CharField(blank=True, max_length=100, verbose_name='車格')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='車種')),
            ],
            options={
                'verbose_name': 'トラック',
                'verbose_name_plural': 'トラック',
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='出荷依頼番号')),
                ('delivery_deadline', models.DateField(verbose_name='お届け日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.destination', verbose_name='配送先')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shipper', verbose_name='荷主')),
            ],
            options={
                'verbose_name': '出荷依頼',
                'verbose_name_plural': '出荷依頼',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanItemLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='個数')),
                ('position_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載位置X座標(cm)')),
                ('position_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載位置Y座標(cm)')),
                ('rotation', models.IntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0, verbose_name='回転角度')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.item', verbose_name='品目')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_loads', to='delivery.deliveryplan')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼')),
            ],
            options={
                'verbose_name': '積載商品',
                'verbose_name_plural': '積載商品',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.item', verbose_name='品目')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='delivery.shippingorder')),
            ],
            options={
                'verbose_name': '出荷商品',
                'verbose_name_plural': '出荷商品',
            },
        ),
        migrations.AddField(
            model_name='deliveryplan',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.truck', verbose_name='トラック'),
        ),
        migrations.CreateModel(
            name='PlanOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_sequence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='配送順序')),
                ('estimated_arrival', models.DateTimeField(verbose_name='到着予定時刻')),
                ('travel_time_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='移動時間(分)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='delivery.deliveryplan')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼')),
            ],
            options={
                'verbose_name': '配送計画明細',
                'verbose_name_plural': '配送計画明細',
                'ordering': ['delivery_sequence'],
                'unique_together': {('plan', 'shipping_order')},
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_code', models.CharField(max_length=100, verbose_name='部品コード')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='幅(cm)')),
                ('depth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='奥行(cm)')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='高さ(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='質量(kg)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='delivery.item')),
            ],
            options={
                'verbose_name': '部品',
                'verbose_name_plural': '部品',
                'unique_together': {('item', 'parts_code')},
            },
        ),
    ]
