# Generated by Django 4.2.7 on 2025-07-11 01:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット番号')),
                ('total_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='総重量(kg)')),
                ('total_volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='総体積(cm³)')),
                ('utilization', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載率(%)')),
            ],
            options={
                'verbose_name': 'パレット詳細',
                'verbose_name_plural': 'パレット詳細',
                'ordering': ['pallet_number'],
            },
        ),
        migrations.CreateModel(
            name='PalletizePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='配送日')),
                ('total_items', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='総商品数')),
                ('total_pallets', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='パレット数')),
                ('total_loose_items', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='バラ積み商品数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'パレタイズ設計',
                'verbose_name_plural': 'パレタイズ設計',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='X座標(cm)')),
                ('position_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Y座標(cm)')),
                ('position_z', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Z座標(cm)')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='幅(cm)')),
                ('depth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='奥行(cm)')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='高さ(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(kg)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.item', verbose_name='品目')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.palletdetail')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.part', verbose_name='部品')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼')),
            ],
            options={
                'verbose_name': 'パレット積載商品',
                'verbose_name_plural': 'パレット積載商品',
            },
        ),
        migrations.AddField(
            model_name='palletdetail',
            name='palletize_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallets', to='delivery.palletizeplan'),
        ),
        migrations.CreateModel(
            name='LooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='幅(cm)')),
                ('depth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='奥行(cm)')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='高さ(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(kg)')),
                ('reason', models.CharField(max_length=100, verbose_name='理由')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.item', verbose_name='品目')),
                ('palletize_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loose_items', to='delivery.palletizeplan')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼')),
            ],
            options={
                'verbose_name': 'バラ積み商品',
                'verbose_name_plural': 'バラ積み商品',
            },
        ),
        migrations.AlterUniqueTogether(
            name='palletdetail',
            unique_together={('palletize_plan', 'pallet_number')},
        ),
    ]
