# Generated by Django 4.2.7 on 2025-07-11 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_palletdetail_palletizeplan_palletitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='設定名')),
                ('width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット幅(cm)')),
                ('depth', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット奥行(cm)')),
                ('max_height', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大積み上げ高さ(cm)')),
                ('max_weight', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='最大積載重量(kg)')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'パレット設定',
                'verbose_name_plural': 'パレット設定',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]