# Generated by Django 4.2.7 on 2025-07-11 02:45

from django.db import migrations


def create_default_pallet_config(apps, schema_editor):
    """デフォルトパレット設定を作成"""
    PalletConfiguration = apps.get_model('delivery', 'PalletConfiguration')
    
    # デフォルト設定が存在しない場合のみ作成
    if not PalletConfiguration.objects.filter(is_default=True).exists():
        PalletConfiguration.objects.create(
            name='標準パレット',
            width=100,
            depth=100,
            max_height=80,
            max_weight=100.0,
            is_default=True
        )


def reverse_default_pallet_config(apps, schema_editor):
    """デフォルトパレット設定を削除"""
    PalletConfiguration = apps.get_model('delivery', 'PalletConfiguration')
    PalletConfiguration.objects.filter(name='標準パレット', is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_palletconfiguration'),
    ]

    operations = [
        migrations.RunPython(create_default_pallet_config, reverse_default_pallet_config),
    ]