# Generated by Django 5.1.0 on 2024-07-11 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_create_default_pallet_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_type', models.CharField(choices=[('REAL', 'パレタイズされたパレット'), ('VIRTUAL', '疑似パレット（バラ積み）')], max_length=20, verbose_name='パレットタイプ')),
                ('delivery_date', models.DateField(verbose_name='配送日')),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット幅(cm)')),
                ('depth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット奥行(cm)')),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット高さ(cm)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='パレット重量(kg)')),
                ('volume', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='パレット体積(cm³)')),
                ('item_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='商品数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.item', verbose_name='品目')),
                ('pallet_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.palletdetail', verbose_name='パレット詳細')),
                ('shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼')),
            ],
            options={
                'verbose_name': '統一パレット',
                'verbose_name_plural': '統一パレット',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載位置X座標(cm)')),
                ('position_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='積載位置Y座標(cm)')),
                ('rotation', models.IntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0, verbose_name='回転角度')),
                ('load_sequence', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='積み込み順序')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.unifiedpallet', verbose_name='パレット')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_pallets', to='delivery.deliveryplan')),
            ],
            options={
                'verbose_name': '積載パレット',
                'verbose_name_plural': '積載パレット',
                'ordering': ['load_sequence'],
            },
        ),
        migrations.CreateModel(
            name='PalletLoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='割り当て日時')),
                ('status', models.CharField(choices=[('ALLOCATED', '割り当て済み'), ('USED', '使用中'), ('COMPLETED', '完了')], default='ALLOCATED', max_length=20, verbose_name='ステータス')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_history', to='delivery.unifiedpallet')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryplan', verbose_name='配送計画')),
            ],
            options={
                'verbose_name': 'パレット積載履歴',
                'verbose_name_plural': 'パレット積載履歴',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='palletloadhistory',
            constraint=models.UniqueConstraint(fields=('pallet', 'plan'), name='unique_pallet_plan'),
        ),
    ]