# Generated by Django 4.2.7 on 2025-07-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_migrate_to_pallet_based'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palletloadhistory',
            name='unique_pallet_plan',
        ),
        migrations.AddField(
            model_name='unifiedpallet',
            name='related_orders',
            field=models.ManyToManyField(blank=True, related_name='unified_pallets', to='delivery.shippingorder', verbose_name='関連する出荷依頼'),
        ),
        migrations.AlterField(
            model_name='unifiedpallet',
            name='shipping_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.shippingorder', verbose_name='出荷依頼'),
        ),
        migrations.AlterUniqueTogether(
            name='palletloadhistory',
            unique_together={('pallet', 'plan')},
        ),
    ]
