services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=logistics_db
      - POSTGRES_USER=logistics_user
      - POSTGRES_PASSWORD=logistics_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logistics_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=logistics_db
      - DB_USER=logistics_user
      - DB_PASS=logistics_pass
      - DEBUG=True
    depends_on:
      - db

volumes:
  postgres_data: